/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'city' : string,
  'state' : string,
  'address' : string,
  'first_name' : string,
  'last_name' : string,
}
export interface AdminDashboardData {
  'orders' : Array<Order>,
  'auditLog' : Array<AuditLogEntry>,
  'userProfiles' : Array<[Principal, UserProfile]>,
  'securityStats' : SecurityStats,
}
export interface AuditLogEntry {
  'action' : string,
  'admin' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export interface Details {
  'dob' : string,
  'zip' : string,
  'height' : string,
  'city' : string,
  'address' : string,
  'gender' : string,
  'first_name' : string,
  'last_name' : string,
  'state_name' : string,
  'id_number' : string,
  'eye_color' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : Status,
  'trackingNumber' : [] | [string],
  'owner' : [] | [Principal],
  'creationTime' : Time,
  'address' : Address,
  'details' : Details,
  'photo' : ExternalBlob,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export interface SecurityEvent {
  'result' : { 'allowed' : null } |
    { 'denied' : null } |
    { 'throttled' : null },
  'principal' : Principal,
  'action' : string,
  'timestamp' : Time,
  'reason' : string,
}
export interface SecurityStats {
  'deniedCalls' : bigint,
  'allowedCalls' : bigint,
  'throttledCalls' : bigint,
}
export type Status = { 'shipped' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'isVIP' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToAllowlist' : ActorMethod<[Principal], undefined>,
  'addToBlocklist' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'bulkApproveOrders' : ActorMethod<[Array<string>], undefined>,
  'bulkDeleteOrders' : ActorMethod<[Array<string>], undefined>,
  'bulkShipOrders' : ActorMethod<[Array<string>], undefined>,
  'clearSecurityCounters' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<
    [string, Details, Address, ExternalBlob],
    undefined
  >,
  'createOrderWithCallback' : ActorMethod<
    [string, Details, Address, ExternalBlob],
    Order
  >,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'exportOrdersCSV' : ActorMethod<[], string>,
  'getAdminDashboard' : ActorMethod<[], AdminDashboardData>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllVIPAccounts' : ActorMethod<[], Array<[Principal, boolean]>>,
  'getAuditLog' : ActorMethod<[bigint], Array<AuditLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getSecurityConfig' : ActorMethod<
    [],
    {
      'blocklistSize' : bigint,
      'allowlistSize' : bigint,
      'rateLimitWindow' : bigint,
      'maxCallsPerWindow' : bigint,
      'enabled' : boolean,
    }
  >,
  'getSecurityEvents' : ActorMethod<[bigint], Array<SecurityEvent>>,
  'getSecurityStats' : ActorMethod<[], SecurityStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminAccess' : ActorMethod<[string], undefined>,
  'grantVIPStatus' : ActorMethod<[Principal], undefined>,
  'isAdminEmail' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerBanned' : ActorMethod<[], boolean>,
  'isCallerVIP' : ActorMethod<[], boolean>,
  'isOrderOwner' : ActorMethod<[string], boolean>,
  'isUserBanned' : ActorMethod<[Principal], boolean>,
  'listAdminEmails' : ActorMethod<[], Array<string>>,
  'removeFromAllowlist' : ActorMethod<[Principal], undefined>,
  'removeFromBlocklist' : ActorMethod<[Principal], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'revokeAdminAccess' : ActorMethod<[string], undefined>,
  'revokeVIPStatus' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSecurityEnabled' : ActorMethod<[boolean], undefined>,
  'setTrackingNumber' : ActorMethod<[string, string], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateRateLimits' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];