/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountInfo {
  'principal' : Principal,
  'orderCount' : bigint,
  'isBanned' : boolean,
  'isVIP' : boolean,
  'profile' : [] | [UserProfile],
}
export interface Address {
  'zip' : string,
  'city' : string,
  'state' : string,
  'address' : string,
  'first_name' : string,
  'last_name' : string,
}
export interface AdminDashboardData {
  'orders' : Array<Order>,
  'auditLog' : Array<AuditLogEntry>,
  'accounts' : Array<AccountInfo>,
  'securityStats' : SecurityStats,
}
export interface AuditLogEntry {
  'action' : string,
  'admin' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export interface Details {
  'dob' : string,
  'zip' : string,
  'height' : string,
  'city' : string,
  'address' : string,
  'gender' : string,
  'first_name' : string,
  'last_name' : string,
  'state_name' : string,
  'id_number' : string,
  'eye_color' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'trackingNumber' : [] | [string],
  'signature' : [] | [ExternalBlob],
  'owner' : [] | [Principal],
  'promoCode' : [] | [string],
  'promoUsed' : boolean,
  'creationTime' : Time,
  'address' : Address,
  'details' : Details,
  'photo' : ExternalBlob,
  'archived' : boolean,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null };
export interface PromoCode {
  'active' : boolean,
  'code' : string,
  'usageLimit' : bigint,
  'timesUsed' : bigint,
  'discountPercentage' : bigint,
  'validUntil' : Time,
}
export interface PromoCodeValidation {
  'valid' : boolean,
  'discountPercentage' : bigint,
}
export interface SecurityStats {
  'deniedCalls' : bigint,
  'allowedCalls' : bigint,
  'throttledCalls' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'isVIP' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'archiveOrder' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'createOrder' : ActorMethod<
    [
      string,
      Details,
      Address,
      ExternalBlob,
      [] | [string],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'createPromoCode' : ActorMethod<[string, bigint, Time, bigint], undefined>,
  'deactivatePromoCode' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'getAccountInfo' : ActorMethod<[Principal], [] | [AccountInfo]>,
  'getAdminDashboard' : ActorMethod<[], AdminDashboardData>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPromoCodes' : ActorMethod<[], Array<PromoCode>>,
  'getArchivedOrders' : ActorMethod<[], Array<Order>>,
  'getAuditLog' : ActorMethod<[], Array<AuditLogEntry>>,
  'getCallerOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getPromoCode' : ActorMethod<[string], [] | [PromoCode]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerVIP' : ActorMethod<[], boolean>,
  'isUserBanned' : ActorMethod<[Principal], boolean>,
  'isUserVIP' : ActorMethod<[Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTrackingNumber' : ActorMethod<[string, string], undefined>,
  'setVIPStatus' : ActorMethod<[Principal, boolean], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'updateOrderDetails' : ActorMethod<[string, Details, Address], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'validatePromoCode' : ActorMethod<[string], PromoCodeValidation>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];