/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OwnerBootstrapStatus = IDL.Record({
  'status' : IDL.Variant({
    'boostrap_succeeded' : IDL.Null,
    'already_admin' : IDL.Null,
  }),
  'adminSaved' : IDL.Bool,
});
export const Details = IDL.Record({
  'dob' : IDL.Text,
  'zip' : IDL.Text,
  'height' : IDL.Text,
  'city' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'first_name' : IDL.Text,
  'last_name' : IDL.Text,
  'state_name' : IDL.Text,
  'id_number' : IDL.Text,
  'eye_color' : IDL.Text,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'first_name' : IDL.Text,
  'last_name' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'isVIP' : IDL.Bool,
});
export const AccountInfo = IDL.Record({
  'principal' : IDL.Principal,
  'orderCount' : IDL.Nat,
  'isBanned' : IDL.Bool,
  'isVIP' : IDL.Bool,
  'profile' : IDL.Opt(UserProfile),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'trackingNumber' : IDL.Opt(IDL.Text),
  'signature' : IDL.Opt(ExternalBlob),
  'owner' : IDL.Opt(IDL.Principal),
  'promoCode' : IDL.Opt(IDL.Text),
  'promoUsed' : IDL.Bool,
  'creationTime' : Time,
  'address' : Address,
  'details' : Details,
  'photo' : ExternalBlob,
  'archived' : IDL.Bool,
});
export const AuditLogEntry = IDL.Record({
  'action' : IDL.Text,
  'admin' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const SecurityStats = IDL.Record({
  'deniedCalls' : IDL.Nat,
  'allowedCalls' : IDL.Nat,
  'throttledCalls' : IDL.Nat,
});
export const AdminDashboardData = IDL.Record({
  'orders' : IDL.Vec(Order),
  'auditLog' : IDL.Vec(AuditLogEntry),
  'accounts' : IDL.Vec(AccountInfo),
  'securityStats' : SecurityStats,
});
export const PromoCode = IDL.Record({
  'active' : IDL.Bool,
  'code' : IDL.Text,
  'usageLimit' : IDL.Nat,
  'timesUsed' : IDL.Nat,
  'discountPercentage' : IDL.Nat,
  'validUntil' : Time,
});
export const TreyCSecurityConfig = IDL.Record({
  'rateLimitWindow' : IDL.Nat,
  'maxCallsPerWindow' : IDL.Nat,
  'enabled' : IDL.Bool,
});
export const TreyCSecurityEvent = IDL.Record({
  'result' : IDL.Variant({
    'allowed' : IDL.Null,
    'denied' : IDL.Null,
    'throttled' : IDL.Null,
  }),
  'principal' : IDL.Principal,
  'action' : IDL.Text,
  'timestamp' : Time,
  'reason' : IDL.Text,
});
export const TreyCSecurityStats = IDL.Record({
  'deniedCalls' : IDL.Nat,
  'allowedCalls' : IDL.Nat,
  'throttledCalls' : IDL.Nat,
});
export const Config = IDL.Record({
  'healthCheckEnabled' : IDL.Bool,
  'version' : IDL.Text,
});
export const HealthCheck = IDL.Record({
  'updateLogs' : IDL.Vec(IDL.Text),
  'isHealthy' : IDL.Bool,
  'version' : IDL.Text,
  'config' : Config,
  'time_ns' : IDL.Int,
});
export const PromoCodeValidation = IDL.Record({
  'valid' : IDL.Bool,
  'discountPercentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'archiveOrder' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'bootstrapOwner' : IDL.Func([], [OwnerBootstrapStatus], []),
  'clearTreyCSecurityEvents' : IDL.Func([], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        Details,
        Address,
        ExternalBlob,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'createPromoCode' : IDL.Func([IDL.Text, IDL.Nat, Time, IDL.Nat], [], []),
  'deactivatePromoCode' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'getAccountInfo' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AccountInfo)],
      ['query'],
    ),
  'getAdminDashboard' : IDL.Func([], [AdminDashboardData], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
  'getArchivedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getPromoCode' : IDL.Func([IDL.Text], [IDL.Opt(PromoCode)], ['query']),
  'getTreyCSecurityConfig' : IDL.Func([], [TreyCSecurityConfig], ['query']),
  'getTreyCSecurityEvents' : IDL.Func(
      [],
      [IDL.Vec(TreyCSecurityEvent)],
      ['query'],
    ),
  'getTreyCSecurityStats' : IDL.Func([], [TreyCSecurityStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [HealthCheck], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerVIP' : IDL.Func([], [IDL.Bool], ['query']),
  'isTreyCSecurityEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isUserVIP' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'resetTreyCSecurityStats' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCanisterId' : IDL.Func([IDL.Principal], [], []),
  'setTrackingNumber' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setTreyCSecurityConfig' : IDL.Func([TreyCSecurityConfig], [], []),
  'setVIPStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'updateConfig' : IDL.Func([Config], [], []),
  'updateOrderDetails' : IDL.Func([IDL.Text, Details, Address], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'validatePromoCode' : IDL.Func([IDL.Text], [PromoCodeValidation], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OwnerBootstrapStatus = IDL.Record({
    'status' : IDL.Variant({
      'boostrap_succeeded' : IDL.Null,
      'already_admin' : IDL.Null,
    }),
    'adminSaved' : IDL.Bool,
  });
  const Details = IDL.Record({
    'dob' : IDL.Text,
    'zip' : IDL.Text,
    'height' : IDL.Text,
    'city' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'first_name' : IDL.Text,
    'last_name' : IDL.Text,
    'state_name' : IDL.Text,
    'id_number' : IDL.Text,
    'eye_color' : IDL.Text,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'first_name' : IDL.Text,
    'last_name' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'isVIP' : IDL.Bool,
  });
  const AccountInfo = IDL.Record({
    'principal' : IDL.Principal,
    'orderCount' : IDL.Nat,
    'isBanned' : IDL.Bool,
    'isVIP' : IDL.Bool,
    'profile' : IDL.Opt(UserProfile),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'trackingNumber' : IDL.Opt(IDL.Text),
    'signature' : IDL.Opt(ExternalBlob),
    'owner' : IDL.Opt(IDL.Principal),
    'promoCode' : IDL.Opt(IDL.Text),
    'promoUsed' : IDL.Bool,
    'creationTime' : Time,
    'address' : Address,
    'details' : Details,
    'photo' : ExternalBlob,
    'archived' : IDL.Bool,
  });
  const AuditLogEntry = IDL.Record({
    'action' : IDL.Text,
    'admin' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const SecurityStats = IDL.Record({
    'deniedCalls' : IDL.Nat,
    'allowedCalls' : IDL.Nat,
    'throttledCalls' : IDL.Nat,
  });
  const AdminDashboardData = IDL.Record({
    'orders' : IDL.Vec(Order),
    'auditLog' : IDL.Vec(AuditLogEntry),
    'accounts' : IDL.Vec(AccountInfo),
    'securityStats' : SecurityStats,
  });
  const PromoCode = IDL.Record({
    'active' : IDL.Bool,
    'code' : IDL.Text,
    'usageLimit' : IDL.Nat,
    'timesUsed' : IDL.Nat,
    'discountPercentage' : IDL.Nat,
    'validUntil' : Time,
  });
  const TreyCSecurityConfig = IDL.Record({
    'rateLimitWindow' : IDL.Nat,
    'maxCallsPerWindow' : IDL.Nat,
    'enabled' : IDL.Bool,
  });
  const TreyCSecurityEvent = IDL.Record({
    'result' : IDL.Variant({
      'allowed' : IDL.Null,
      'denied' : IDL.Null,
      'throttled' : IDL.Null,
    }),
    'principal' : IDL.Principal,
    'action' : IDL.Text,
    'timestamp' : Time,
    'reason' : IDL.Text,
  });
  const TreyCSecurityStats = IDL.Record({
    'deniedCalls' : IDL.Nat,
    'allowedCalls' : IDL.Nat,
    'throttledCalls' : IDL.Nat,
  });
  const Config = IDL.Record({
    'healthCheckEnabled' : IDL.Bool,
    'version' : IDL.Text,
  });
  const HealthCheck = IDL.Record({
    'updateLogs' : IDL.Vec(IDL.Text),
    'isHealthy' : IDL.Bool,
    'version' : IDL.Text,
    'config' : Config,
    'time_ns' : IDL.Int,
  });
  const PromoCodeValidation = IDL.Record({
    'valid' : IDL.Bool,
    'discountPercentage' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'archiveOrder' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'bootstrapOwner' : IDL.Func([], [OwnerBootstrapStatus], []),
    'clearTreyCSecurityEvents' : IDL.Func([], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          Details,
          Address,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'createPromoCode' : IDL.Func([IDL.Text, IDL.Nat, Time, IDL.Nat], [], []),
    'deactivatePromoCode' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'getAccountInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AccountInfo)],
        ['query'],
      ),
    'getAdminDashboard' : IDL.Func([], [AdminDashboardData], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
    'getArchivedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getPromoCode' : IDL.Func([IDL.Text], [IDL.Opt(PromoCode)], ['query']),
    'getTreyCSecurityConfig' : IDL.Func([], [TreyCSecurityConfig], ['query']),
    'getTreyCSecurityEvents' : IDL.Func(
        [],
        [IDL.Vec(TreyCSecurityEvent)],
        ['query'],
      ),
    'getTreyCSecurityStats' : IDL.Func([], [TreyCSecurityStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [HealthCheck], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerVIP' : IDL.Func([], [IDL.Bool], ['query']),
    'isTreyCSecurityEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isUserVIP' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'resetTreyCSecurityStats' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCanisterId' : IDL.Func([IDL.Principal], [], []),
    'setTrackingNumber' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setTreyCSecurityConfig' : IDL.Func([TreyCSecurityConfig], [], []),
    'setVIPStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'updateConfig' : IDL.Func([Config], [], []),
    'updateOrderDetails' : IDL.Func([IDL.Text, Details, Address], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'validatePromoCode' : IDL.Func(
        [IDL.Text],
        [PromoCodeValidation],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };